export enum RequiredEnvVariablesEnum {
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_TOKEN_EXPIRE_TIME = 'ACCESS_TOKEN_EXPIRE_TIME',
  REFRESH_TOKEN_EXPIRE_TIME = 'REFRESH_TOKEN_EXPIRE_TIME',
  REFRESH_SECRET = 'REFRESH_SECRET',
  ACCESS_SECRET = 'ACCESS_SECRET',
  EMAIL_ID = 'EMAIL_ID',
  EMAIL_PASS = 'EMAIL_PASS',
  PORT = 'PORT',
  DELIVERY_MS_HOST = 'DELIVERY_MS_HOST',
  DELIVERY_MS_PORT = 'DELIVERY_MS_PORT',
  AUTH_MS_HOST = 'AUTH_MS_HOST',
  AUTH_MS_PORT = 'AUTH_MS_PORT',
}

export enum MicroServicesEnum {
  DELIVERY_MS = 'DELIVERY_MS',
  AUTH_MS = 'AUTH_MS',
}
